# _config.yml
title: Vaxonyx
url: "https://shivakumar1509.github.io"   # REQUIRED for project sites
baseurl: "/VaxonyxAI"                      # REQUIRED for project sites

markdown: kramdown
permalink: pretty
