# _config.yml  â€” Default (GitHub Pages)
title: Vaxonyx
markdown: kramdown
theme: null
plugins: []
permalink: pretty

# GitHub Pages project URL
url: "https://shivakumar1509.github.io"
baseurl: "/VaxonyxAI"

# Bump this whenever you change CSS/JS to clear browser cache
assets_version: "30"

# Default exclusions
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
  - amplify.yml
  - _config_aws.yml
