# _config.yml  â€” default for GitHub Pages
title: Vaxonyx
markdown: kramdown
theme: null
plugins: []
permalink: pretty

# GitHub Pages project URL
url: "https://shivakumar1509.github.io"
baseurl: "/VaxonyxAI"

# bump when you change CSS/JS
assets_version: "25"

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
