title: Vaxonyx
markdown: kramdown
theme: null
plugins: []
permalink: pretty
# Leave these blank by default so site works anywhere
url: ""
baseurl: ""

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
