title: Vaxonyx
url: "https://shivakumar1509.github.io"   # hosting base
baseurl: "/VaxonyxAI"                     # project subfolder (critical)
markdown: kramdown
theme: null
plugins: []
exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
